server:
  port: 8000
spring:
  profiles:
    active: prod
    include: feign
  application:
    name: service-order
  cloud:
    nacos:
      server-addr: 150.158.27.19:8848
      # 这里禁用检查禁止掉 = false,不然会报错
      config:
        import-check:
          enabled: false
          # 这里的含义是如果 pring.profiles.active 没有激活的话，则使用 public 命名空间下的配置
        namespace: ${spring.profiles.active:public}

seata:
  enabled: false

logging:
  level:
    com.atguigu.order.feign: debug

---
spring:
  config:
    import:
      - nacos:common.properties?group=order
      - nacos:database.properties?group=order
    activate:
      on-profile: dev
---
spring:
  config:
    import:
      - nacos:common.properties?group=order
      - nacos:database.properties?group=order
      - nacos:haha.properties?group=order
    activate:
      on-profile: test
---
spring:
  config:
    import:
      - nacos:common.properties?group=order
      - nacos:database.properties?group=order
      - nacos:hehe.properties?group=order
    activate:
      on-profile: prod