spring.application.name=service-product

server.port=9000

spring.cloud.nacos.server-addr=150.158.27.19:8848
spring.cloud.nacos.config.import-check.enabled=false
#spring.cloud.sentinel.transport.dashboard=localhost:8080
#spring.cloud.sentinel.eager=true

# Disable Seata auto-configuration
seata.enabled=false
spring.cloud.alibaba.seata.enabled=false
